### ISSUE TITLE
Move clampAngle() to a utilities script and make it non-recursive

### ISSUE THREAD

**Issue by pklito** [pauloalbert/Achtung-remake#5]
technically non optimal as it is now, and if another script wants to replicate the same clamping functionability, they have to implement their own version, which results in **code repetition**

I suggest rather than doing it recursively, running `angle = angle % 2*PI`.
_(note, in most programming languages -2%10 returns -2, not 8)_

**Comment by Alebereto** [comment]
Function is now not recursive under VectorUtilities
